### ISSUE TITLE
New warning generated.

### ISSUE THREAD

**Issue by asgr** [asgr/Rfits#11]
With a new Mac OS and clang updated etc, I see a new warning:

clang -mmacosx-version-min=10.13 -c -o ./eval_l.o -Wall -g -O2 -Dg77Fortran -fPIC -fno-common  -DPACKAGE_NAME=\"\" -DPACKAGE_TARNAME=\"\" -DPACKAGE_VERSION=\"\" -DPACKAGE_STRING=\"\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MATH_H=1 -DHAVE_LIMITS_H=1 -D_LARGEFILE_SOURCE=1 -D_FILE_OFFSET_BITS=64 -DHAVE_FTRUNCATE=1 -DHAVE_LONGLONG=1 -DHAVE_SHMEM_SERVICES=1 -DHAVE_UNION_SEMUN=1 -DHAVE_FMEMOPEN=1 -DHAVE_NET_SERVICES=1 eval_l.c
<stdout>:1750:17: warning: unused function 'ffunput' [-Wunused-function]
    static void ffunput (int c, register char * ff_bp )
                ^
<stdout>:1791:16: warning: function 'input' is not needed and will not be emitted [-Wunneeded-internal-declaration]
    static int input  (void)
               ^

**Comment by asgr** [comment]
Not sure if the right answer is to just comment the following block out in eval_l.c

Line 1787 onwards:

#ifndef FF_NO_INPUT
#ifdef __cplusplus
    static int ffinput (void)
#else
    static int input  (void)
#endif

**Comment by rtobar** [comment]
This was due to `eval_l.c` being generated with a very (2008) old version of flex. I've re-generated it, plus set additional options to avoid emitting some unnecessary code. Please try the `warning-free-eval` branch with the changes.

**Comment by asgr** [comment]
Passing all my tests and the CRAN checks now- looks good to go!

**Comment by rtobar** [comment]
Merged to `master` now.
