### ISSUE TITLE
Legacy header format support

### ISSUE THREAD

**Issue by SabineBellstedt** [asgr/Rfits#2]
In order to save an image with a header, it is currently necessary to specify keynames and keyvalues separately as the input to Rfits_save_image. 

Numerous codes refer to a list-style header, and therefore it would be useful to either have access to a function that converts this header into the associated keynames and keyvalues, or to be able to input this header format directly into the Rfits_save_image function.

**Comment by asgr** [comment]
Good suggestion! It has now been added- just meant exposing some internal functions.
